import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/client/NavBar";

export const metadata: Metadata = {
  title: "Blog Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
